/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hallmanagementsystem;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import static hallmanagementsystem.HallManagementSystem.buildTableModel;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Collection;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author sonjoy
 */
public class SupervisorFrame extends javax.swing.JFrame {

    private String action;
    private String std_id;
    private String name;
    private String res_status;
    private String dept;
    private String blood_group;
    private String address;
    private String room_no;
    private String mess_card_no;
    private String term;
    private String level;
    private String library_id;
    private String phone_no;

    private String searchtype;
    private String searchid;
    
    
    private String day,month,year,scroll,ammount,feeType;

    private Connection connection;

    private showStudentData showStdData;
    private Insertion insertRecord;
    
    
   

    public SupervisorFrame(Connection con) throws SQLException {
        connection = con;

        initComponents();
        //studentIdLebel.setVisible(false);
        //studentidtextfieldforsearch.setVisible(false);
        searchButton.setVisible(false);
        showStdData = new showStudentData(con);
        insertRecord = new Insertion(con);
        
        
        dueStdlabel.setVisible(!true);
              dueStudentIDTextField.setVisible(!true);
              dueLevelCombo.setVisible(!true);
              dueTermCombo.setVisible(!true);
              
              dueLeveltermlabel.setVisible(!true);
              

    }

    public void resizeTableColumn(JTable sstudentDataTable) {

        for (int column = 0; column < sstudentDataTable.getColumnCount(); column++) {
            TableColumn tableColumn = sstudentDataTable.getColumnModel().getColumn(column);

            int preferredWidth = tableColumn.getWidth();

            int maxWidth = tableColumn.getMaxWidth();

            Object value = tableColumn.getHeaderValue();
            TableCellRenderer renderer = tableColumn.getHeaderRenderer();

            if (renderer == null) {
                renderer = sstudentDataTable.getTableHeader().getDefaultRenderer();
            }

            Component hc = renderer.getTableCellRendererComponent(sstudentDataTable, value, false, false, -1, column);
            int headWidth = hc.getPreferredSize().width + sstudentDataTable.getIntercellSpacing().width;
            preferredWidth = Math.max(preferredWidth, headWidth);
            for (int row = 0; row < sstudentDataTable.getRowCount(); row++) {
                TableCellRenderer cellRenderer = sstudentDataTable.getCellRenderer(row, column);
                Component c = sstudentDataTable.prepareRenderer(cellRenderer, row, column);
                int width = c.getPreferredSize().width + sstudentDataTable.getIntercellSpacing().width;
                preferredWidth = Math.max(preferredWidth, width);

                if (preferredWidth >= maxWidth) {
                    preferredWidth = maxWidth;
                    break;
                }
                tableColumn.setPreferredWidth(preferredWidth);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supervisorTabbedPan = new javax.swing.JTabbedPane();
        studentDbTabbedPan = new javax.swing.JTabbedPane();
        insertStudentPan = new javax.swing.JPanel();
        studentIDLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        resStatusLabel = new javax.swing.JLabel();
        termLabel = new javax.swing.JLabel();
        roomNoLable = new javax.swing.JLabel();
        libCardLabel = new javax.swing.JLabel();
        messCardLabel = new javax.swing.JLabel();
        bloodLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        studentIdText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        levelCombo = new javax.swing.JComboBox<>();
        termCombo = new javax.swing.JComboBox<>();
        residentCombo = new javax.swing.JComboBox<>();
        phoneNoText = new javax.swing.JTextField();
        permanentAddresslabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextField = new javax.swing.JTextArea();
        roomNoText = new javax.swing.JTextField();
        messCardText = new javax.swing.JTextField();
        hallLibraryCardText = new javax.swing.JTextField();
        addStudentRecordButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        starStdName = new javax.swing.JLabel();
        starPhone = new javax.swing.JLabel();
        deptCombo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        actionTypecombo = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        bloodGroupCombo = new javax.swing.JComboBox<>();
        viewStudentDbPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        searchOptionCombo = new javax.swing.JComboBox<>();
        studentIdLebel = new javax.swing.JLabel();
        studentidtextfieldforsearch = new javax.swing.JTextField();
        showButton = new javax.swing.JButton();
        showStudentPanel = new javax.swing.JPanel();
        showtudentDataScroll = new javax.swing.JScrollPane();
        studentDataTable = new javax.swing.JTable();
        updatePaymentPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        studentIDPaymentTextField = new javax.swing.JTextField();
        feeTypeCombo = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        monthCombo = new javax.swing.JComboBox<>();
        dayCombo = new javax.swing.JComboBox<>();
        yearTextField = new javax.swing.JTextField();
        ammountTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        scrollTextField = new javax.swing.JTextField();
        updatePaymentButton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        addDueButton = new javax.swing.JPanel();
        dueStudentTypeCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dueLeveltermlabel = new javax.swing.JLabel();
        dueStdlabel = new javax.swing.JLabel();
        dueLevelCombo = new javax.swing.JComboBox<>();
        dueTermCombo = new javax.swing.JComboBox<>();
        dueStudentIDTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        dueFineTextField = new javax.swing.JTextField();
        dueDayCombo = new javax.swing.JComboBox<>();
        dueMonthCombo = new javax.swing.JComboBox<>();
        dueYearTextField = new javax.swing.JTextField();
        dueYearLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dueFeeTypeCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        supervisorTabbedPan.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        insertStudentPan.setForeground(new java.awt.Color(244, 15, 15));
        insertStudentPan.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        studentIDLabel.setText("Student ID");

        nameLabel.setText("Name");

        phoneLabel.setText("Phone No.");

        deptLabel.setText("Dept.");

        resStatusLabel.setText("Resident Status");

        termLabel.setText("Term");

        roomNoLable.setText("Room No.");

        libCardLabel.setText("Hall Library Card No.");

        messCardLabel.setText("Mess Card No.");

        bloodLabel.setText("Blood Group");

        levelLabel.setText("Level");

        levelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        termCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        residentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Resident", "Attatched", " " }));
        residentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residentComboActionPerformed(evt);
            }
        });

        permanentAddresslabel.setText("Permanent Address");

        addressTextField.setColumns(20);
        addressTextField.setRows(5);
        jScrollPane1.setViewportView(addressTextField);

        addStudentRecordButton.setText("Update / Add");
        addStudentRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentRecordButtonActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(234, 0, 0));
        jLabel13.setText("*");

        starStdName.setForeground(new java.awt.Color(234, 0, 0));
        starStdName.setText("*");

        starPhone.setForeground(new java.awt.Color(234, 0, 0));
        starPhone.setText("*");

        deptCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "EEE", "ME", "IPE", "CE", "Ch.E", "NAME", "URP", "WRE", "Arch.", " " }));

        jLabel19.setText("Select Option");

        actionTypecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add New Record", "Update Record" }));
        actionTypecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionTypecomboActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        bloodGroupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Blood Group", "A+", "AB+", "B+", "O+", "A-", "AB-", "B-", "O-", " " }));
        bloodGroupCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertStudentPanLayout = new javax.swing.GroupLayout(insertStudentPan);
        insertStudentPan.setLayout(insertStudentPanLayout);
        insertStudentPanLayout.setHorizontalGroup(
            insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertStudentPanLayout.createSequentialGroup()
                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertStudentPanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertStudentPanLayout.createSequentialGroup()
                                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deptLabel)
                                    .addComponent(levelLabel)
                                    .addComponent(resStatusLabel)
                                    .addComponent(bloodLabel))
                                .addGap(58, 58, 58)
                                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(residentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(levelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bloodGroupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(insertStudentPanLayout.createSequentialGroup()
                                .addComponent(phoneLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(starPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(insertStudentPanLayout.createSequentialGroup()
                                .addComponent(studentIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(79, 79, 79)
                                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(insertStudentPanLayout.createSequentialGroup()
                                        .addComponent(termLabel)
                                        .addGap(36, 36, 36)
                                        .addComponent(termCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(insertStudentPanLayout.createSequentialGroup()
                                        .addComponent(studentIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(searchButton))))
                            .addGroup(insertStudentPanLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(70, 70, 70)
                                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(actionTypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(insertStudentPanLayout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(starStdName)))
                        .addGap(116, 116, 116)
                        .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(permanentAddresslabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(insertStudentPanLayout.createSequentialGroup()
                                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roomNoLable)
                                    .addComponent(messCardLabel)
                                    .addComponent(libCardLabel))
                                .addGap(41, 41, 41)
                                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hallLibraryCardText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(messCardText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roomNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(insertStudentPanLayout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(addStudentRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        insertStudentPanLayout.setVerticalGroup(
            insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertStudentPanLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(actionTypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel)
                    .addComponent(permanentAddresslabel)
                    .addComponent(starStdName))
                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertStudentPanLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentIdText)
                            .addComponent(studentIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(searchButton))
                        .addGap(33, 33, 33)
                        .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deptLabel)
                            .addComponent(deptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(levelLabel)
                            .addComponent(levelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(termLabel)
                            .addComponent(termCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel)
                            .addComponent(phoneNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomNoLable)
                            .addComponent(roomNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(starPhone))
                        .addGap(26, 26, 26)
                        .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resStatusLabel)
                            .addComponent(residentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(insertStudentPanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertStudentPanLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(messCardLabel)
                            .addComponent(messCardText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertStudentPanLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodLabel)
                            .addComponent(bloodGroupCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 102, Short.MAX_VALUE))
                    .addGroup(insertStudentPanLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(insertStudentPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(libCardLabel)
                            .addComponent(hallLibraryCardText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(addStudentRecordButton)
                        .addGap(22, 22, 22))))
        );

        studentDbTabbedPan.addTab("Update / Add New Student Record", insertStudentPan);

        jLabel16.setText("Select Option");

        searchOptionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Resident", "Attatched", "Specific" }));
        searchOptionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOptionComboActionPerformed(evt);
            }
        });

        studentIdLebel.setText("Student ID");

        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        studentDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        studentDataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        showtudentDataScroll.setViewportView(studentDataTable);

        javax.swing.GroupLayout showStudentPanelLayout = new javax.swing.GroupLayout(showStudentPanel);
        showStudentPanel.setLayout(showStudentPanelLayout);
        showStudentPanelLayout.setHorizontalGroup(
            showStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showStudentPanelLayout.createSequentialGroup()
                .addComponent(showtudentDataScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        showStudentPanelLayout.setVerticalGroup(
            showStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showStudentPanelLayout.createSequentialGroup()
                .addComponent(showtudentDataScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout viewStudentDbPanelLayout = new javax.swing.GroupLayout(viewStudentDbPanel);
        viewStudentDbPanel.setLayout(viewStudentDbPanelLayout);
        viewStudentDbPanelLayout.setHorizontalGroup(
            viewStudentDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewStudentDbPanelLayout.createSequentialGroup()
                .addGroup(viewStudentDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewStudentDbPanelLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(viewStudentDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentIdLebel)
                            .addComponent(jLabel16))
                        .addGap(68, 68, 68)
                        .addGroup(viewStudentDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchOptionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentidtextfieldforsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(viewStudentDbPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(showStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewStudentDbPanelLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewStudentDbPanelLayout.setVerticalGroup(
            viewStudentDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewStudentDbPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(viewStudentDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchOptionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(29, 29, 29)
                .addGroup(viewStudentDbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdLebel)
                    .addComponent(studentidtextfieldforsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showButton)
                .addGap(41, 41, 41)
                .addComponent(showStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentDbTabbedPan.addTab("View Student Record", viewStudentDbPanel);

        supervisorTabbedPan.addTab("Student Database", studentDbTabbedPan);

        jLabel7.setText("Student ID");

        jLabel8.setText("Fee Type");

        jLabel9.setText("Payment Date");

        jLabel12.setText("Ammount");

        jLabel17.setText("Bank Scroll No.");

        feeTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Fee Type", "Mess Charge", "Hall Fee(Resident)", "Hall Fee(Attatched)", "Identity Card", "Aditional Charge" }));

        jLabel18.setText("Day");

        jLabel20.setText("Month");

        jLabel21.setText("Year");

        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        monthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboActionPerformed(evt);
            }
        });

        dayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });

        jLabel22.setText("taka");

        updatePaymentButton.setText("Update");
        updatePaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePaymentButtonActionPerformed(evt);
            }
        });

        jLabel24.setForeground(new java.awt.Color(233, 14, 14));
        jLabel24.setText("*");

        jLabel25.setForeground(new java.awt.Color(233, 14, 14));
        jLabel25.setText("*");

        jLabel26.setForeground(new java.awt.Color(233, 14, 14));
        jLabel26.setText("*");

        javax.swing.GroupLayout updatePaymentPanelLayout = new javax.swing.GroupLayout(updatePaymentPanel);
        updatePaymentPanel.setLayout(updatePaymentPanelLayout);
        updatePaymentPanelLayout.setHorizontalGroup(
            updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                        .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                                .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8))
                                .addGap(36, 36, 36))
                            .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ammountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scrollTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel22)
                                    .addContainerGap())
                                .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                                            .addComponent(studentIDPaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                                            .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel20)
                                            .addGap(18, 18, 18)
                                            .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                            .addComponent(jLabel21)
                                            .addGap(26, 26, 26)
                                            .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap(87, Short.MAX_VALUE)))))
                            .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(feeTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(updatePaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updatePaymentPanelLayout.setVerticalGroup(
            updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePaymentPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(studentIDPaymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(33, 33, 33)
                .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel25)
                    .addComponent(jLabel18)
                    .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(feeTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ammountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(updatePaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(scrollTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(updatePaymentButton)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        supervisorTabbedPan.addTab("Update Payment", updatePaymentPanel);

        dueStudentTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student Type", "Resident ", "Attatched", "Level/Term", "Specific", "All", " ", " " }));
        dueStudentTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueStudentTypeComboActionPerformed(evt);
            }
        });

        jButton1.setText("Add Due");

        jLabel1.setText("Select Student");

        dueLeveltermlabel.setText("Select Level / Term");

        dueStdlabel.setText("Student ID");

        dueLevelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "1", "2", "3", "4", "5" }));

        dueTermCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Term", "1", "2" }));

        jLabel4.setText("Fee Type");

        jLabel5.setText("Amount");

        jLabel6.setText("Last Payment Date");

        jLabel10.setText("Fine Per Day After Last Date");

        dueDayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        dueMonthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));

        dueYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueYearTextFieldActionPerformed(evt);
            }
        });

        dueYearLabel.setText("Year");

        jLabel2.setText("Taka");

        dueFeeTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Fee Type", "Mess Charge", "Hall Fee(Resident)", "Hall Fee(Attatched)", "Identity Card", "Aditional Charge" }));

        javax.swing.GroupLayout addDueButtonLayout = new javax.swing.GroupLayout(addDueButton);
        addDueButton.setLayout(addDueButtonLayout);
        addDueButtonLayout.setHorizontalGroup(
            addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDueButtonLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueLeveltermlabel)
                    .addComponent(dueStdlabel)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDueButtonLayout.createSequentialGroup()
                        .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addDueButtonLayout.createSequentialGroup()
                                .addComponent(dueDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(dueMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(dueYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(dueYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addDueButtonLayout.createSequentialGroup()
                                .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dueFineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addDueButtonLayout.createSequentialGroup()
                                        .addComponent(dueLevelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dueTermCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dueStudentIDTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dueStudentTypeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(addDueButtonLayout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addDueButtonLayout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(93, 93, 93))
                    .addGroup(addDueButtonLayout.createSequentialGroup()
                        .addComponent(dueFeeTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        addDueButtonLayout.setVerticalGroup(
            addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDueButtonLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dueStudentTypeCombo))
                .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDueButtonLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(dueStdlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dueLeveltermlabel))
                    .addGroup(addDueButtonLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dueStudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dueLevelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dueTermCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDueButtonLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addGroup(addDueButtonLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dueFeeTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDueButtonLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6))
                    .addGroup(addDueButtonLayout.createSequentialGroup()
                        .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addDueButtonLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dueDayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dueMonthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dueYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dueYearLabel)))))
                .addGap(26, 26, 26)
                .addGroup(addDueButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dueFineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        supervisorTabbedPan.addTab("Update Dues", addDueButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(supervisorTabbedPan)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(supervisorTabbedPan, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
        searchtype = searchOptionCombo.getSelectedItem().toString();
        searchid = studentidtextfieldforsearch.getText();

        String quaryforsearch;
        ResultSet rs;

        if (searchtype.equals("All")) {
            try {

                DefaultTableModel tableModel = (DefaultTableModel) showStdData.showAllStudents();
                studentDataTable.setModel(tableModel);
                studentDataTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                resizeTableColumn(studentDataTable);

            } catch (SQLException ex) {
                Logger.getLogger(SupervisorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (searchtype.equals("Specific")) {
            if (searchid.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter a student Id");
            } else {

                try {
                    DefaultTableModel tableModel = (DefaultTableModel) showStdData.specificStudent(searchid);
                    studentDataTable.setModel(tableModel);
                    studentDataTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                    resizeTableColumn(studentDataTable);

                } catch (SQLException ex) {
                    Logger.getLogger(SupervisorFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else if (searchtype.equals("Attatched")) {
            try {

                DefaultTableModel tableModel = (DefaultTableModel) showStdData.showAttachedStudents();
                studentDataTable.setModel(tableModel);
                studentDataTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                resizeTableColumn(studentDataTable);

            } catch (SQLException ex) {
                Logger.getLogger(SupervisorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (searchtype.equals("Resident")) {
            try {

                DefaultTableModel tableModel = (DefaultTableModel) showStdData.showResidentStudents();
                studentDataTable.setModel(tableModel);
                studentDataTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                resizeTableColumn(studentDataTable);

            } catch (SQLException ex) {
                Logger.getLogger(SupervisorFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_showButtonActionPerformed

    private void addStudentRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentRecordButtonActionPerformed
        // TODO add your handling code here:
        action = actionTypecombo.getSelectedItem().toString();
        
        std_id = studentIdText.getText();
        name = nameText.getText();
        res_status = residentCombo.getSelectedItem().toString();
        dept = deptCombo.getSelectedItem().toString();
        level = levelCombo.getSelectedItem().toString();
        term = termCombo.getSelectedItem().toString();
        phone_no = phoneNoText.getText();
        room_no = roomNoText.getText();
        mess_card_no = messCardText.getText();
        library_id = hallLibraryCardText.getText();
        address = addressTextField.getText();
        
        if (action.equals("Add New Record")) {
            insertRecord.insertStudentRecord(std_id, name, res_status, room_no, mess_card_no, term, level, phone_no, dept, library_id, blood_group, address);
                    
        }


    }//GEN-LAST:event_addStudentRecordButtonActionPerformed

    private void searchOptionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOptionComboActionPerformed
        // TODO add your handling code here:
        //studentDataTable.setVisible(false);
        searchtype = searchOptionCombo.getSelectedItem().toString();
        if (searchtype.equals("Specific")) {
            //showtudentDataScroll.setVisible(false);
            studentIdLebel.setVisible(true);
            studentidtextfieldforsearch.setVisible(true);
        } else if (searchtype.equals("All")) {
            // showtudentDataScroll.setVisible(false);
            studentIdLebel.setVisible(false);
            studentidtextfieldforsearch.setVisible(false);
        }
        else if (searchtype.equals("Attatched")) {
            // showtudentDataScroll.setVisible(false);
            studentIdLebel.setVisible(false);
            studentidtextfieldforsearch.setVisible(false);
        }
        else if (searchtype.equals("Resident")) {
            // showtudentDataScroll.setVisible(false);
            studentIdLebel.setVisible(false);
            studentidtextfieldforsearch.setVisible(false);
        }
    }//GEN-LAST:event_searchOptionComboActionPerformed

    private void residentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residentComboActionPerformed
        // TODO add your handling code here:
        res_status = residentCombo.getSelectedItem().toString();
        if (res_status.equals("Attatched")) {
            roomNoLable.setVisible(false);
            roomNoText.setVisible(false);
            messCardLabel.setVisible(false);
            messCardText.setVisible(false);
            libCardLabel.setVisible(false);
            hallLibraryCardText.setVisible(false);
        } else {
            roomNoLable.setVisible(true);
            roomNoText.setVisible(true);
            messCardLabel.setVisible(true);
            messCardText.setVisible(true);
            libCardLabel.setVisible(true);
            hallLibraryCardText.setVisible(true);
        }
    }//GEN-LAST:event_residentComboActionPerformed

    private void bloodGroupComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupComboActionPerformed
        // TODO add your handling code here:
        blood_group=bloodGroupCombo.getSelectedItem().toString();
        if(blood_group.equals("Select Blood Group"))
        {
            blood_group="null";
        }
        
    }//GEN-LAST:event_bloodGroupComboActionPerformed

    private void monthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthComboActionPerformed

    private void updatePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePaymentButtonActionPerformed
        // TODO add your handling code here:
        std_id=studentIDPaymentTextField.getText();
        scroll=scrollTextField.getText();
        ammount=ammountTextField.getText();
        day=dayCombo.getSelectedItem().toString();
        month=monthCombo.getSelectedItem().toString();
        year=yearTextField.getText();
        feeType=feeTypeCombo.getSelectedItem().toString();
        
        if(std_id.equals("") || scroll.equals("")|| day.equals("Select Day") || month.equals("Select Month") ||year.equals("") )    
        {
            JOptionPane.showMessageDialog(null, "Please Enter at least * marked fields");
            
        }
        else if(year.length()<4 && year.length() != 2)
        {
            JOptionPane.showMessageDialog(null, "Please Enter Year Correctly");
            
        }
        else
        {
            if(year.length() == 2)
                year = "20"+year;
            
            insertRecord.insertPayment(std_id, feeType, ammount, day,month, year,scroll);
        }
        
    }//GEN-LAST:event_updatePaymentButtonActionPerformed

    private void actionTypecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionTypecomboActionPerformed
        // TODO add your handling code here:
        String actionType = actionTypecombo.getSelectedItem().toString();
        if(actionType.equals("Update Record"))
        {
            nameLabel.setVisible(false);
            nameText.setVisible(false);
            permanentAddresslabel.setVisible(false);
            addressTextField.setVisible(false);
            deptLabel.setVisible(false);
            deptCombo.setVisible(false);
            levelLabel.setVisible(false);
            levelCombo.setVisible(false);
            termLabel.setVisible(false);
            termCombo.setVisible(false);
            phoneLabel.setVisible(false);
            phoneNoText.setVisible(false);
            resStatusLabel.setVisible(false);
            residentCombo.setVisible(false);
            bloodLabel.setVisible(false);
            bloodGroupCombo.setVisible(false);
            roomNoLable.setVisible(false);
            roomNoText.setVisible(false);
            messCardLabel.setVisible(false);
            messCardText.setVisible(false);
            hallLibraryCardText.setVisible(false);
            libCardLabel.setVisible(false);
            searchButton.setVisible(true);
            studentIDLabel.setVisible(true);
            studentIdText.setVisible(true);
            starPhone.setVisible(false);
            starStdName.setVisible(false);
            
        }
        else
        {
            nameLabel.setVisible(!false);
            nameText.setVisible(!false);
            permanentAddresslabel.setVisible(!false);
            addressTextField.setVisible(true);
            deptLabel.setVisible(!false);
            deptCombo.setVisible(!false);
            levelLabel.setVisible(!false);
            levelCombo.setVisible(!false);
            termLabel.setVisible(!false);
            termCombo.setVisible(!false);
            phoneLabel.setVisible(!false);
            phoneNoText.setVisible(!false);
            resStatusLabel.setVisible(!false);
            residentCombo.setVisible(!false);
            bloodLabel.setVisible(!false);
            bloodGroupCombo.setVisible(!false);
            roomNoLable.setVisible(!false);
            roomNoText.setVisible(!false);
            messCardLabel.setVisible(!false);
            messCardText.setVisible(!false);
            hallLibraryCardText.setVisible(!false);
            libCardLabel.setVisible(!false);
            searchButton.setVisible(false);
            starPhone.setVisible(!false);
            starStdName.setVisible(!false);
        }
    }//GEN-LAST:event_actionTypecomboActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        std_id = studentIdText.getText();
        String query = "select * from STUDENTS where student_id = "+std_id;
        
        Statement statement;
        try {
            statement = connection.createStatement();
            ResultSet    rs = statement.executeQuery(query);
            
        } catch (SQLException ex) {
            Logger.getLogger(SupervisorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_searchButtonActionPerformed

    private void dueStudentTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueStudentTypeComboActionPerformed
        // TODO add your handling code here:
          String dueSelectstdType;
          dueSelectstdType=dueStudentTypeCombo.getSelectedItem().toString();
          if(dueSelectstdType.equals("Specific"))
          {
              dueStdlabel.setVisible(true);
              dueStudentIDTextField.setVisible(true);
              dueLevelCombo.setVisible(!true);
              dueTermCombo.setVisible(!true);
              
              dueLeveltermlabel.setVisible(!true);
              
              
          }
          else if (dueSelectstdType.equals("Level/Term"))
          {
              dueLevelCombo.setVisible(true);
              dueTermCombo.setVisible(true);
              
              dueLeveltermlabel.setVisible(true);
              
              dueStdlabel.setVisible(!true);
              dueStudentIDTextField.setVisible(!true);
              
          }
          else
          {
              dueStdlabel.setVisible(!true);
              dueStudentIDTextField.setVisible(!true);
              dueLevelCombo.setVisible(!true);
              dueTermCombo.setVisible(!true);
              
              dueLeveltermlabel.setVisible(!true);
              
          }
          
        
    }//GEN-LAST:event_dueStudentTypeComboActionPerformed

    private void dueYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dueYearTextFieldActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> actionTypecombo;
    private javax.swing.JPanel addDueButton;
    private javax.swing.JButton addStudentRecordButton;
    private javax.swing.JTextArea addressTextField;
    private javax.swing.JTextField ammountTextField;
    private javax.swing.JComboBox<String> bloodGroupCombo;
    private javax.swing.JLabel bloodLabel;
    private javax.swing.JComboBox<String> dayCombo;
    private javax.swing.JComboBox<String> deptCombo;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JComboBox<String> dueDayCombo;
    private javax.swing.JComboBox<String> dueFeeTypeCombo;
    private javax.swing.JTextField dueFineTextField;
    private javax.swing.JComboBox<String> dueLevelCombo;
    private javax.swing.JLabel dueLeveltermlabel;
    private javax.swing.JComboBox<String> dueMonthCombo;
    private javax.swing.JLabel dueStdlabel;
    private javax.swing.JTextField dueStudentIDTextField;
    private javax.swing.JComboBox<String> dueStudentTypeCombo;
    private javax.swing.JComboBox<String> dueTermCombo;
    private javax.swing.JLabel dueYearLabel;
    private javax.swing.JTextField dueYearTextField;
    private javax.swing.JComboBox<String> feeTypeCombo;
    private javax.swing.JTextField hallLibraryCardText;
    private javax.swing.JPanel insertStudentPan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> levelCombo;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel libCardLabel;
    private javax.swing.JLabel messCardLabel;
    private javax.swing.JTextField messCardText;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel permanentAddresslabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneNoText;
    private javax.swing.JLabel resStatusLabel;
    private javax.swing.JComboBox<String> residentCombo;
    private javax.swing.JLabel roomNoLable;
    private javax.swing.JTextField roomNoText;
    private javax.swing.JTextField scrollTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchOptionCombo;
    private javax.swing.JButton showButton;
    private javax.swing.JPanel showStudentPanel;
    private javax.swing.JScrollPane showtudentDataScroll;
    private javax.swing.JLabel starPhone;
    private javax.swing.JLabel starStdName;
    private javax.swing.JTable studentDataTable;
    private javax.swing.JTabbedPane studentDbTabbedPan;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JTextField studentIDPaymentTextField;
    private javax.swing.JLabel studentIdLebel;
    private javax.swing.JTextField studentIdText;
    private javax.swing.JTextField studentidtextfieldforsearch;
    private javax.swing.JTabbedPane supervisorTabbedPan;
    private javax.swing.JComboBox<String> termCombo;
    private javax.swing.JLabel termLabel;
    private javax.swing.JButton updatePaymentButton;
    private javax.swing.JPanel updatePaymentPanel;
    private javax.swing.JPanel viewStudentDbPanel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
